language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t marcovgurrola/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true marcovgurrola/react-test npm test

after_success:
  - docker build -t marcovgurrola/multi-client ./client
  - docker build -t marcovgurrola/multi-nginx ./nginx
  - docker build -t marcovgurrola/multi-server ./server
  - docker build -t marcovgurrola/multi-worker ./worker